### ISSUE TITLE
Rozpisać flow ticketów

### ISSUE THREAD

**Issue by ppogorzelczyk** [kapeluszk/soft-eng-put#1]

**Comment by kapeluszk** [comment]
dobra ogarnięte flow strony - zaraz ogarnę dla ticketów 

[https://putpoznanpl-my.sharepoint.com/:u:/g/personal/kacper_grzelak_student_put_poznan_pl/EXym6a6by8JDh8FVgbUzNbsBZdZeseG6WTdlE5_aE-zeNQ?e=tCoRvt](url)

**Comment by kapeluszk** [comment]
najbanalniejsze flow ticketów jakie widzieliście

[https://putpoznanpl-my.sharepoint.com/:u:/g/personal/kacper_grzelak_student_put_poznan_pl/EeovyydSpthPmVLj0i3hnRsBQ-L7BI9FnZYXtxhX3qP4dw?e=rYSVEo](url)

**Comment by kapeluszk** [comment]
na tickety powinny być dwie osobne tabele

1.  tabela incydentów 
2.  tabela "requestów"

ticket powinien być zbudowany w następujący sposób:

1.  typ ticketu
2.  autor
3.  kolejka - o ile zaimplementujemy kolejki
4.  temat
5.  treść
6.  status  ticketu - open/closed/ew. on hold
7.  data utworzenia ticketu
8.  właściciel ticketu (agent)
