### ISSUE TITLE
Zaimplementować Gin

### ISSUE THREAD

**Issue by ppogorzelczyk** [kapeluszk/soft-eng-put#10]
Obecnie API jest napisane z paczką "net/http", chcemy skorzystać z Gina więc trzeba to przerobić
Bare minimum żeby po prostu móc strzelić /ping

**Comment by kapeluszk** [comment]
![Image](https://github.com/kapeluszk/soft-eng-put/assets/126521076/cfb3a0cf-3139-4410-a732-ba8e67eaf726)
