### ISSUE TITLE
Zrobić diagram przypadków użycia

### ISSUE THREAD

**Issue by ppogorzelczyk** [kapeluszk/soft-eng-put#15]

**Comment by ppogorzelczyk** [comment]
https://docs.google.com/document/d/1XSyZr1Z-5WinCurmn1u1bwLKQhM7DTVxccOdQAdIPIA/edit?usp=sharing

**Comment by bartoszkorszun** [comment]
Przypadki użycia:

- User:
  - Utworzenie ticketu
  - Odczytanie odpowiedzi
- Admin:
  - Utworzenie agenta
  - Utworzenie usera
- Agent:
  - Przypisanie zgłoszenia
  - Realizacja zgłoszenia
- Agent Leader:
  - Przypisanie zgłoszenia
  - Weryfikacja raportów
