### ISSUE TITLE
Zrobić diagram kontekstu

### ISSUE THREAD

**Issue by ppogorzelczyk** [kapeluszk/soft-eng-put#8]

**Comment by bartoszkorszun** [comment]
Diagram ma zawierać interacje systemu z czynnikami zewnętrznymi typu userzy. W takim przypadku będzie to wyglądało tak:

Core:
- System ticketowy

Czynniki i interakcje:
- user
	- utworzenie ticketu (request)
	- odczytanie odpowiedzi (response)
- admin
	- utworzenie agenta (request)
	- utworzenie usera (request)
- agent
	- otrzymanie ticketu (response)
	- rozwiązanie/odpowiedź (request)
- agent leader
	- raporty/statystyki (response)
	- przypisywanie ticketów (request)
- baza
	- zapisanie danych (request)
	- odczytanie danych (response)

**Comment by bartoszkorszun** [comment]
![Image](https://github.com/kapeluszk/soft-eng-put/assets/61890250/ed48f12a-c6c8-4222-b496-44565dda3649)
